// Generated by gencpp from file gripper_besturing/gripperServiceMessage.msg
// DO NOT EDIT!


#ifndef GRIPPER_BESTURING_MESSAGE_GRIPPERSERVICEMESSAGE_H
#define GRIPPER_BESTURING_MESSAGE_GRIPPERSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <gripper_besturing/gripperServiceMessageRequest.h>
#include <gripper_besturing/gripperServiceMessageResponse.h>


namespace gripper_besturing
{

struct gripperServiceMessage
{

typedef gripperServiceMessageRequest Request;
typedef gripperServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gripperServiceMessage
} // namespace gripper_besturing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gripper_besturing::gripperServiceMessage > {
  static const char* value()
  {
    return "c9aa0baea7a9c0e9e50fcc3986fdf213";
  }

  static const char* value(const ::gripper_besturing::gripperServiceMessage&) { return value(); }
};

template<>
struct DataType< ::gripper_besturing::gripperServiceMessage > {
  static const char* value()
  {
    return "gripper_besturing/gripperServiceMessage";
  }

  static const char* value(const ::gripper_besturing::gripperServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::gripper_besturing::gripperServiceMessageRequest> should match
// service_traits::MD5Sum< ::gripper_besturing::gripperServiceMessage >
template<>
struct MD5Sum< ::gripper_besturing::gripperServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_besturing::gripperServiceMessage >::value();
  }
  static const char* value(const ::gripper_besturing::gripperServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_besturing::gripperServiceMessageRequest> should match
// service_traits::DataType< ::gripper_besturing::gripperServiceMessage >
template<>
struct DataType< ::gripper_besturing::gripperServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::gripper_besturing::gripperServiceMessage >::value();
  }
  static const char* value(const ::gripper_besturing::gripperServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gripper_besturing::gripperServiceMessageResponse> should match
// service_traits::MD5Sum< ::gripper_besturing::gripperServiceMessage >
template<>
struct MD5Sum< ::gripper_besturing::gripperServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_besturing::gripperServiceMessage >::value();
  }
  static const char* value(const ::gripper_besturing::gripperServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_besturing::gripperServiceMessageResponse> should match
// service_traits::DataType< ::gripper_besturing::gripperServiceMessage >
template<>
struct DataType< ::gripper_besturing::gripperServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::gripper_besturing::gripperServiceMessage >::value();
  }
  static const char* value(const ::gripper_besturing::gripperServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRIPPER_BESTURING_MESSAGE_GRIPPERSERVICEMESSAGE_H
