# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision_message/vision_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class vision_msg(genpy.Message):
  _md5sum = "52237def187f2c19b70d40056e5fd89f"
  _type = "vision_message/vision_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Pose vision_positie
std_msgs/String object_naam

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['vision_positie','object_naam']
  _slot_types = ['geometry_msgs/Pose','std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vision_positie,object_naam

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(vision_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vision_positie is None:
        self.vision_positie = geometry_msgs.msg.Pose()
      if self.object_naam is None:
        self.object_naam = std_msgs.msg.String()
    else:
      self.vision_positie = geometry_msgs.msg.Pose()
      self.object_naam = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.vision_positie.position.x, _x.vision_positie.position.y, _x.vision_positie.position.z, _x.vision_positie.orientation.x, _x.vision_positie.orientation.y, _x.vision_positie.orientation.z, _x.vision_positie.orientation.w))
      _x = self.object_naam.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vision_positie is None:
        self.vision_positie = geometry_msgs.msg.Pose()
      if self.object_naam is None:
        self.object_naam = std_msgs.msg.String()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.vision_positie.position.x, _x.vision_positie.position.y, _x.vision_positie.position.z, _x.vision_positie.orientation.x, _x.vision_positie.orientation.y, _x.vision_positie.orientation.z, _x.vision_positie.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_naam.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_naam.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.vision_positie.position.x, _x.vision_positie.position.y, _x.vision_positie.position.z, _x.vision_positie.orientation.x, _x.vision_positie.orientation.y, _x.vision_positie.orientation.z, _x.vision_positie.orientation.w))
      _x = self.object_naam.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.vision_positie is None:
        self.vision_positie = geometry_msgs.msg.Pose()
      if self.object_naam is None:
        self.object_naam = std_msgs.msg.String()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.vision_positie.position.x, _x.vision_positie.position.y, _x.vision_positie.position.z, _x.vision_positie.orientation.x, _x.vision_positie.orientation.y, _x.vision_positie.orientation.z, _x.vision_positie.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_naam.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_naam.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
