// Auto-generated. Do not edit!

// (in-package manipulator_groep_1.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class control_robotResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.succeeded = null;
    }
    else {
      if (initObj.hasOwnProperty('succeeded')) {
        this.succeeded = initObj.succeeded
      }
      else {
        this.succeeded = new std_msgs.msg.Bool();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type control_robotResult
    // Serialize message field [succeeded]
    bufferOffset = std_msgs.msg.Bool.serialize(obj.succeeded, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type control_robotResult
    let len;
    let data = new control_robotResult(null);
    // Deserialize message field [succeeded]
    data.succeeded = std_msgs.msg.Bool.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'manipulator_groep_1/control_robotResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '97c94fffdbfad2245b6980b4b9910754';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    
    std_msgs/Bool succeeded
    
    ================================================================================
    MSG: std_msgs/Bool
    bool data
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new control_robotResult(null);
    if (msg.succeeded !== undefined) {
      resolved.succeeded = std_msgs.msg.Bool.Resolve(msg.succeeded)
    }
    else {
      resolved.succeeded = new std_msgs.msg.Bool()
    }

    return resolved;
    }
};

module.exports = control_robotResult;
