// Generated by gencpp from file manipulator_groep_1/control_robotResult.msg
// DO NOT EDIT!


#ifndef MANIPULATOR_GROEP_1_MESSAGE_CONTROL_ROBOTRESULT_H
#define MANIPULATOR_GROEP_1_MESSAGE_CONTROL_ROBOTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace manipulator_groep_1
{
template <class ContainerAllocator>
struct control_robotResult_
{
  typedef control_robotResult_<ContainerAllocator> Type;

  control_robotResult_()
    : succeeded()  {
    }
  control_robotResult_(const ContainerAllocator& _alloc)
    : succeeded(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _succeeded_type;
  _succeeded_type succeeded;





  typedef boost::shared_ptr< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> const> ConstPtr;

}; // struct control_robotResult_

typedef ::manipulator_groep_1::control_robotResult_<std::allocator<void> > control_robotResult;

typedef boost::shared_ptr< ::manipulator_groep_1::control_robotResult > control_robotResultPtr;
typedef boost::shared_ptr< ::manipulator_groep_1::control_robotResult const> control_robotResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulator_groep_1::control_robotResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulator_groep_1::control_robotResult_<ContainerAllocator1> & lhs, const ::manipulator_groep_1::control_robotResult_<ContainerAllocator2> & rhs)
{
  return lhs.succeeded == rhs.succeeded;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulator_groep_1::control_robotResult_<ContainerAllocator1> & lhs, const ::manipulator_groep_1::control_robotResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulator_groep_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97c94fffdbfad2245b6980b4b9910754";
  }

  static const char* value(const ::manipulator_groep_1::control_robotResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97c94fffdbfad224ULL;
  static const uint64_t static_value2 = 0x5b6980b4b9910754ULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulator_groep_1/control_robotResult";
  }

  static const char* value(const ::manipulator_groep_1::control_robotResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"\n"
"std_msgs/Bool succeeded\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::manipulator_groep_1::control_robotResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeeded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct control_robotResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulator_groep_1::control_robotResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulator_groep_1::control_robotResult_<ContainerAllocator>& v)
  {
    s << indent << "succeeded: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.succeeded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATOR_GROEP_1_MESSAGE_CONTROL_ROBOTRESULT_H
