(cl:defpackage gripper_besturing-srv
  (:use )
  (:export
   "GRIPPERSERVICEMESSAGE"
   "<GRIPPERSERVICEMESSAGE-REQUEST>"
   "GRIPPERSERVICEMESSAGE-REQUEST"
   "<GRIPPERSERVICEMESSAGE-RESPONSE>"
   "GRIPPERSERVICEMESSAGE-RESPONSE"
  ))

