(cl:defpackage manipulator_groep_1-msg
  (:use )
  (:export
   "<CONTROL_ROBOTACTION>"
   "CONTROL_ROBOTACTION"
   "<CONTROL_ROBOTACTIONFEEDBACK>"
   "CONTROL_ROBOTACTIONFEEDBACK"
   "<CONTROL_ROBOTACTIONGOAL>"
   "CONTROL_ROBOTACTIONGOAL"
   "<CONTROL_ROBOTACTIONRESULT>"
   "CONTROL_ROBOTACTIONRESULT"
   "<CONTROL_ROBOTFEEDBACK>"
   "CONTROL_ROBOTFEEDBACK"
   "<CONTROL_ROBOTGOAL>"
   "CONTROL_ROBOTGOAL"
   "<CONTROL_ROBOTRESULT>"
   "CONTROL_ROBOTRESULT"
  ))

