; Auto-generated. Do not edit!


(cl:in-package manipulator_groep_1-msg)


;//! \htmlinclude control_robotFeedback.msg.html

(cl:defclass <control_robotFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass control_robotFeedback (<control_robotFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <control_robotFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'control_robotFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name manipulator_groep_1-msg:<control_robotFeedback> is deprecated: use manipulator_groep_1-msg:control_robotFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <control_robotFeedback>) ostream)
  "Serializes a message object of type '<control_robotFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <control_robotFeedback>) istream)
  "Deserializes a message object of type '<control_robotFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<control_robotFeedback>)))
  "Returns string type for a message object of type '<control_robotFeedback>"
  "manipulator_groep_1/control_robotFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'control_robotFeedback)))
  "Returns string type for a message object of type 'control_robotFeedback"
  "manipulator_groep_1/control_robotFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<control_robotFeedback>)))
  "Returns md5sum for a message object of type '<control_robotFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'control_robotFeedback)))
  "Returns md5sum for a message object of type 'control_robotFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<control_robotFeedback>)))
  "Returns full string definition for message of type '<control_robotFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'control_robotFeedback)))
  "Returns full string definition for message of type 'control_robotFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <control_robotFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <control_robotFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'control_robotFeedback
))
