; Auto-generated. Do not edit!


(cl:in-package manipulator_groep_1-msg)


;//! \htmlinclude control_robotGoal.msg.html

(cl:defclass <control_robotGoal> (roslisp-msg-protocol:ros-message)
  ((lineairpose
    :reader lineairpose
    :initarg :lineairpose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose))
   (position
    :reader position
    :initarg :position
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String))
   (mode
    :reader mode
    :initarg :mode
    :type std_msgs-msg:Bool
    :initform (cl:make-instance 'std_msgs-msg:Bool)))
)

(cl:defclass control_robotGoal (<control_robotGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <control_robotGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'control_robotGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name manipulator_groep_1-msg:<control_robotGoal> is deprecated: use manipulator_groep_1-msg:control_robotGoal instead.")))

(cl:ensure-generic-function 'lineairpose-val :lambda-list '(m))
(cl:defmethod lineairpose-val ((m <control_robotGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader manipulator_groep_1-msg:lineairpose-val is deprecated.  Use manipulator_groep_1-msg:lineairpose instead.")
  (lineairpose m))

(cl:ensure-generic-function 'position-val :lambda-list '(m))
(cl:defmethod position-val ((m <control_robotGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader manipulator_groep_1-msg:position-val is deprecated.  Use manipulator_groep_1-msg:position instead.")
  (position m))

(cl:ensure-generic-function 'mode-val :lambda-list '(m))
(cl:defmethod mode-val ((m <control_robotGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader manipulator_groep_1-msg:mode-val is deprecated.  Use manipulator_groep_1-msg:mode instead.")
  (mode m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <control_robotGoal>) ostream)
  "Serializes a message object of type '<control_robotGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'lineairpose) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'position) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'mode) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <control_robotGoal>) istream)
  "Deserializes a message object of type '<control_robotGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'lineairpose) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'position) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'mode) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<control_robotGoal>)))
  "Returns string type for a message object of type '<control_robotGoal>"
  "manipulator_groep_1/control_robotGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'control_robotGoal)))
  "Returns string type for a message object of type 'control_robotGoal"
  "manipulator_groep_1/control_robotGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<control_robotGoal>)))
  "Returns md5sum for a message object of type '<control_robotGoal>"
  "e36f01127625ad1eec9d70ff2f265799")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'control_robotGoal)))
  "Returns md5sum for a message object of type 'control_robotGoal"
  "e36f01127625ad1eec9d70ff2f265799")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<control_robotGoal>)))
  "Returns full string definition for message of type '<control_robotGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%geometry_msgs/Pose lineairpose~%~%std_msgs/String position~%~%std_msgs/Bool mode~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'control_robotGoal)))
  "Returns full string definition for message of type 'control_robotGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%~%geometry_msgs/Pose lineairpose~%~%std_msgs/String position~%~%std_msgs/Bool mode~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <control_robotGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'lineairpose))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'position))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'mode))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <control_robotGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'control_robotGoal
    (cl:cons ':lineairpose (lineairpose msg))
    (cl:cons ':position (position msg))
    (cl:cons ':mode (mode msg))
))
