; Auto-generated. Do not edit!


(cl:in-package manipulator_groep_1-msg)


;//! \htmlinclude control_robotResult.msg.html

(cl:defclass <control_robotResult> (roslisp-msg-protocol:ros-message)
  ((succeeded
    :reader succeeded
    :initarg :succeeded
    :type std_msgs-msg:Bool
    :initform (cl:make-instance 'std_msgs-msg:Bool)))
)

(cl:defclass control_robotResult (<control_robotResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <control_robotResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'control_robotResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name manipulator_groep_1-msg:<control_robotResult> is deprecated: use manipulator_groep_1-msg:control_robotResult instead.")))

(cl:ensure-generic-function 'succeeded-val :lambda-list '(m))
(cl:defmethod succeeded-val ((m <control_robotResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader manipulator_groep_1-msg:succeeded-val is deprecated.  Use manipulator_groep_1-msg:succeeded instead.")
  (succeeded m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <control_robotResult>) ostream)
  "Serializes a message object of type '<control_robotResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'succeeded) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <control_robotResult>) istream)
  "Deserializes a message object of type '<control_robotResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'succeeded) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<control_robotResult>)))
  "Returns string type for a message object of type '<control_robotResult>"
  "manipulator_groep_1/control_robotResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'control_robotResult)))
  "Returns string type for a message object of type 'control_robotResult"
  "manipulator_groep_1/control_robotResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<control_robotResult>)))
  "Returns md5sum for a message object of type '<control_robotResult>"
  "97c94fffdbfad2245b6980b4b9910754")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'control_robotResult)))
  "Returns md5sum for a message object of type 'control_robotResult"
  "97c94fffdbfad2245b6980b4b9910754")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<control_robotResult>)))
  "Returns full string definition for message of type '<control_robotResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%~%std_msgs/Bool succeeded~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'control_robotResult)))
  "Returns full string definition for message of type 'control_robotResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%~%std_msgs/Bool succeeded~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <control_robotResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'succeeded))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <control_robotResult>))
  "Converts a ROS message object to a list"
  (cl:list 'control_robotResult
    (cl:cons ':succeeded (succeeded msg))
))
