# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hmi/HMI_state.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HMI_state(genpy.Message):
  _md5sum = "12d2ece259040b0ded5a9b3526331ec2"
  _type = "hmi/HMI_state"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string programstate
string programtype
bool stop
bool noodstop
bool stopreset
"""
  __slots__ = ['programstate','programtype','stop','noodstop','stopreset']
  _slot_types = ['string','string','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       programstate,programtype,stop,noodstop,stopreset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HMI_state, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.programstate is None:
        self.programstate = ''
      if self.programtype is None:
        self.programtype = ''
      if self.stop is None:
        self.stop = False
      if self.noodstop is None:
        self.noodstop = False
      if self.stopreset is None:
        self.stopreset = False
    else:
      self.programstate = ''
      self.programtype = ''
      self.stop = False
      self.noodstop = False
      self.stopreset = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.programstate
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.programtype
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.stop, _x.noodstop, _x.stopreset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.programstate = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.programstate = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.programtype = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.programtype = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.stop, _x.noodstop, _x.stopreset,) = _get_struct_3B().unpack(str[start:end])
      self.stop = bool(self.stop)
      self.noodstop = bool(self.noodstop)
      self.stopreset = bool(self.stopreset)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.programstate
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.programtype
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.stop, _x.noodstop, _x.stopreset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.programstate = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.programstate = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.programtype = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.programtype = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.stop, _x.noodstop, _x.stopreset,) = _get_struct_3B().unpack(str[start:end])
      self.stop = bool(self.stop)
      self.noodstop = bool(self.noodstop)
      self.stopreset = bool(self.stopreset)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
