# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from manipulator_groep_1/control_robotGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class control_robotGoal(genpy.Message):
  _md5sum = "e36f01127625ad1eec9d70ff2f265799"
  _type = "manipulator_groep_1/control_robotGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal

geometry_msgs/Pose lineairpose

std_msgs/String position

std_msgs/Bool mode

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: std_msgs/Bool
bool data"""
  __slots__ = ['lineairpose','position','mode']
  _slot_types = ['geometry_msgs/Pose','std_msgs/String','std_msgs/Bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lineairpose,position,mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(control_robotGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.lineairpose is None:
        self.lineairpose = geometry_msgs.msg.Pose()
      if self.position is None:
        self.position = std_msgs.msg.String()
      if self.mode is None:
        self.mode = std_msgs.msg.Bool()
    else:
      self.lineairpose = geometry_msgs.msg.Pose()
      self.position = std_msgs.msg.String()
      self.mode = std_msgs.msg.Bool()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.lineairpose.position.x, _x.lineairpose.position.y, _x.lineairpose.position.z, _x.lineairpose.orientation.x, _x.lineairpose.orientation.y, _x.lineairpose.orientation.z, _x.lineairpose.orientation.w))
      _x = self.position.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.mode.data
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.lineairpose is None:
        self.lineairpose = geometry_msgs.msg.Pose()
      if self.position is None:
        self.position = std_msgs.msg.String()
      if self.mode is None:
        self.mode = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.lineairpose.position.x, _x.lineairpose.position.y, _x.lineairpose.position.z, _x.lineairpose.orientation.x, _x.lineairpose.orientation.y, _x.lineairpose.orientation.z, _x.lineairpose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.position.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.position.data = str[start:end]
      start = end
      end += 1
      (self.mode.data,) = _get_struct_B().unpack(str[start:end])
      self.mode.data = bool(self.mode.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.lineairpose.position.x, _x.lineairpose.position.y, _x.lineairpose.position.z, _x.lineairpose.orientation.x, _x.lineairpose.orientation.y, _x.lineairpose.orientation.z, _x.lineairpose.orientation.w))
      _x = self.position.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.mode.data
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.lineairpose is None:
        self.lineairpose = geometry_msgs.msg.Pose()
      if self.position is None:
        self.position = std_msgs.msg.String()
      if self.mode is None:
        self.mode = std_msgs.msg.Bool()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.lineairpose.position.x, _x.lineairpose.position.y, _x.lineairpose.position.z, _x.lineairpose.orientation.x, _x.lineairpose.orientation.y, _x.lineairpose.orientation.z, _x.lineairpose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.position.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.position.data = str[start:end]
      start = end
      end += 1
      (self.mode.data,) = _get_struct_B().unpack(str[start:end])
      self.mode.data = bool(self.mode.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
